# Generated by Django 3.1.1 on 2022-03-01 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_sellerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amountAvailable',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
